@startuml
金辉大厦 -> 商务: 提供大厦公司资料
商务 -> 安徽软件外包: 系统合作商谈
activate 安徽软件外包
return 提供系统详细资料
note right
1、方案介绍文档
2、设计文档（技术选型说明、架构、数据流等）
3、部署文档
4、API文档
5、软件工程说明
6、质量体系相关文档
end note

商务 -> 安徽软件外包: 确认购买
note left
1.购买功能列表
2.现有价格
3.待扩展功能价格
4.购买服务项内容
end note
return 提供源码调试以及部署支持

商务 -> 餐饮门店: 接入商谈
return 注册
note right
1.商家注册
2.商品填写
end note

@enduml