@startuml
启动 -> 自动导航: 按照固定导航路线运动
自动导航 -> 静止服务: 1.遇到主动上前的人类
activate 静止服务
静止服务 -> 避障:超过一定时间没有交互操作
deactivate
activate 避障
避障 --> 自动导航:躲避开障碍物继续向前运动
deactivate

自动导航 -> 静止服务: 1.遇到主动上前的人类
activate 静止服务
静止服务 -> 用户购物:用户进行扫码操作
deactivate
activate 用户购物
用户购物 -->自动导航:用户完成购买操作取出商品离开
deactivate

自动导航 -> 静止服务: 2.进入拥挤环境
activate 静止服务
return 判断拥挤环境已消失

自动导航 -> 避障:遇到非人类障碍物
activate 避障
return 躲避开障碍物继续向前运动
@enduml