@startuml

:一级代理:as 酒店
:二级代理:as 商家

酒店 --> (提交入驻平台账号申请)
平台 -->(进行申请审核)
(提交入驻平台账号申请)<..(进行申请审核)
平台 --> (开通一级代理账号)
(进行申请审核)<..(开通一级代理账号)

酒店 --> (开通一级代理账号)
商家 -->(提交入驻一级代理账号申请)
(开通一级代理账号)<..(提交入驻一级代理账号申请)
酒店 -->(进行二级代理入驻申请审核)
(提交入驻一级代理账号申请)<..(进行二级代理入驻申请审核)
酒店 -->(提交开通二级代理账号申请)
(进行二级代理入驻申请审核)<..(提交开通二级代理账号申请)
平台 -->(开通二级代理账号)
平台 -->(提交开通二级代理账号申请)
商家 -->(进行二级代理入驻申请审核)
(提交开通二级代理账号申请)<..(开通二级代理账号)

商家 -->(编辑售卖的商品信息)
(开通二级代理账号)<..(编辑售卖的商品信息)
商家 -->(提交发布商品信息申请)
平台 -->(审核商品信息)
note left of (审核商品信息)
1.图片
2.敏感字
end note
(编辑售卖的商品信息)<..(提交发布商品信息申请)
(提交发布商品信息申请)<..(审核商品信息)
(审核商品信息)<..(商品发布)
商家 -->(商品发布)
@enduml