@startuml
:用户: as user
:平台: as platform
:商铺: as shop

user --> (预定分类)
(预定分类)<..(选择预定商品):include
user --> (选择预定商品)
user --> (支付订单)
(选择预定商品)<..(支付订单):include

shop --> (现有产品增加预定标识，预定时间、日期)
shop --> (发布产品到预定分类)
(现有产品增加预定标识，预定时间、日期)<..(发布产品到预定分类):include

platform --> (阿里云自动审核)
(发布产品到预定分类)<..(阿里云自动审核):include
(选择预定商品)<..(商品发布上线):extend

platform ---> (商品发布上线)
shop ---> (商品发布上线)
(阿里云自动审核)<..(商品发布上线):extend
@enduml